version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    command: python run.py
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    volumes:
      - .:/app
    networks:
      - flask-network
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flask-network

networks:
  flask-network:
    driver: bridge

volumes:
  postgres_data:
