version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    command: gunicorn -b 0.0.0.0:8000 run:app
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    volumes:
      - .:/app
    networks:
      - flask-network

networks:
  flask-network:
    driver: bridge
